name: Pull Request Messenger
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Echo and Fail
        id: echo-fail
        continue-on-error: true
        shell: bash
        run: |
          ls -lah | tee output.txt
          OUTPUT=$(cat output.txt)
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=contents::$OUTPUT"
          exit 1

      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the existing comments.

            const {data: comments} = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
            })
            const botComment = comments.find(comment => comment.user.id === 41898282)
            console.log(`Comment ${botComment}`)
            var msg = `### The Salt Project Needs **Your** Help

            <details>
            <summary>Please check the following and see if you can help.</summary>
            <pre>${{ steps.echo-fail.outputs.contents }}</pre>
            </details>`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
