name: Pull Request Messenger
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Echo and Fail
        id: echo-fail
        continue-on-error: true
        shell: bash
        run: |
          ls -lah | tee output.txt
          echo "::set-output name=contents::$(cat output.txt)"
          exit 1

      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var msg = `### The Salt Project Needs **Your** Help

            <details>
            <summary>Please check the following and see if you can help.</summary>
            <pre>${{ steps.echo-fail.outputs.contents }}</pre>
            </details>`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
