name: New Issues Triage Assignment
concurrency: 1
on:
  issues:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: .last-user-assigned
          key: ${{ hashFiles('.last-user-assigned') }}|hashFiles('.github/workflows/scripts/label-and-assign.py')

      - name: Label And Assign Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          READ_ORG_TOKEN: ${{ secrets.READ_ORG_TEAM_MEMBERS_ISSUE_TRIAGE }}
        run: |
          python .github/workflows/scripts/label-and-assign.py \
            --org ${{ github.repository_owner }} \
            --repo ${{ github.repository }} \
            --team team-core \
            --label needs-triage \
            --issue ${{ github.event.issue.id }}
