name: New Issues Triage Assignment
on:
  issues:
    types: [opened]

jobs:
  triage-and-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get Team Members
            team = github.teams.getByName({
              team_slug: 'team-core'
            })
            console.log(team)

            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-triage']
            })
